### PR TITLE
Moving to fuel. Fixes #332.

### LINKED ISSUE #332: Fuel
Before we diverge much further, it would be nice if we switch to Fuel. It should be a very simple renaming task.

### PR DESCRIPTION
**Pull request by bartvm**

### CODE REVIEW

**Comment by rizar** [comment]
Did you move the recently committed `SortMapping` to `Fuel`?

**Comment by bartvm** [comment]
Yes, I `diff`ed all the files to make sure they're up to date.

**Comment by bartvm** [comment]
So I think this is ready considering all the tests pass, @rizar let me know if I can merge!

**Comment by rizar** [comment]
LGTM!

**Comment by bartvm** [comment]
Actually, Travis seems broken currently. It claims success because `coverage combine` exited successfully, but the tests are failing... Need to fix that first.

**Comment by rizar** [comment]
I would consider writing a mail-list announcement: everybody (including me) must now clean their scripts from `blocks.datasets`.

**Comment by bartvm** [comment]
Good point, I'll quickly make one.

**Pull request merged**
