### PR TITLE
Ccw 663

### PR DESCRIPTION
**Pull request by mducoffe**
I have made the changes with WEIGHTS/WEIGHT BIASES/BIAS FILTERS/FILTER but I can't help thinking that every related function are plural as well so it is confusing to use the singular now. Anyway let me know if there are still changes to do

### CODE REVIEW

**Comment by bartvm** [comment]
Something went wrong with merging I think, there are lots of merge conflicts part of this PR (the <<<<< and >>>>> lines)

**Comment by dwf** [comment]
Yeah, I think you had a merge or rebase failure. Let me know if you need help resolving it.

**Comment by mducoffe** [comment]
No it is okay, I will correct it tonight

Mélanie

2015-03-11 21:48 GMT+01:00 David Warde-Farley <notifications@github.com>:

**Comment by mducoffe** [comment]
@dwf , @bartvm Hey, I have an error like some BIASES still remain in the blocks/bricks/__init__.py
Hower I have checked and on the line there is no BIASES and I have removed every BIASES :
blocks/bricks/__init__.py:277:21: F821 undefined name 'BIASES'

Any idea how to solve that ?
Thanks

**Comment by dwf** [comment]
Try deleting any `__pycache__` directories or `.pyc` files.

I still see two references to `WEIGHTS` in the docstrings of `roles.py`.

**Comment by dwf** [comment]
Somehow this has gotten merged with some existing history on master... I couldn't quite figure out how to repair the situation.

Since you did do your part, I don't want to punish you with figuring out the intricacies of git that give even me a headache, so I'd recommend you start fresh. I could do this myself but I think it'll be a good learning experience for you (and I'll give you a command that will automate the replacements so you don't have to do that again).

1. Set up Bart's repository as a remote. We'll call it "upstream".

```bash
git remote add upstream git@github.com:bartvm/blocks.git
```

2. Fetch from his remote.

```bash
git fetch upstream
```

3. Checkout a fresh branch from his remote's "master" branch.

```bash
git checkout -b ccw_363_2 upstream/master
```

4. Use this magical command:

```bash
    for fn in `find . |grep py$`; do cp $fn $fn.old; sed -e s/WEIGHTS/WEIGHT/g -e s/FILTERS/FILTER/g -e s/BIASES/BIAS/g $fn.old >$fn; rm -f $fn.old; done
```

5. Step through the changes. 

```bash
git add -p
```
Hit **y** to accept each one.

6. Commit.

```bash
git commit -m"Rename roles to be singular. Fixes #363."
```

7. Push to origin (assuming origin is mducoffe/blocks.git; you can check with `git remote -v`).

```bash
git push -u origin ccw_363_2:ccw_363_2
```

8. Send a pull request from that branch.

**Comment by dwf** [comment]
See #482.

**Pull request closed without merging**
