### PR TITLE
Fixing recurrent

### PR DESCRIPTION
**Pull request by laurent-dinh**
Just an alternative to fixing the documentation.

### CODE REVIEW

**Comment by rizar** [comment]
In general I like the idea, but code is convoluted. Seems like the code above is equivalent

```python
outputs_info = [
    states_given[name] in name in application.states
    else None 
    for name in application.outputs]
```

**Comment by laurent-dinh** [comment]
Yes, I just replaced it. Also changing the (`scan_function`)[https://github.com/bartvm/blocks/blob/master/blocks/bricks/recurrent.py#L185] so as to take into account the order.

**Comment by rizar** [comment]
Okay. Can you please turn your gist into a test?

**Comment by rizar** [comment]
Ping! You have a test, just add it to `tests/bricks/test_recurrent.py` and that would be it.

**Comment by laurent-dinh** [comment]
Done.

**Comment by rizar** [comment]
Thanks!

**Pull request merged**
