### PR TITLE
Custom pickle

### PR DESCRIPTION
**Pull request by dmitriy-serdyuk**
I started to port this code to theano dump/load.

### CODE REVIEW

**Comment by bartvm** [comment]
You've got some seriously weird history there!

**Comment by dmitriy-serdyuk** [comment]
Fixed.

**Comment by dmitriy-serdyuk** [comment]
@bartvm , can you enable tests for this branch?

**Comment by bartvm** [comment]
Travis doesn't like your branch for some reason. It says:
```
PR #607 received (HEAD commit not updated)
  4f3f18d - Used dump/load from theano
  received at: 2015-04-30 15:54:59
```

**Comment by dmitriy-serdyuk** [comment]
Strange.. It's probably because of `push -f`.

**Pull request closed without merging**
