### PR TITLE
Set names for initial states of recurrent bricks

### PR DESCRIPTION
**Pull request by dmitriy-serdyuk**
Currently it is really hard to debug complicated recurrent structures like ones with sequence generators. This is going to help to distinguish different initial states.

### CODE REVIEW

**Comment by rizar** [comment]
I understand it can be helpful, but this is quite a dirty hack. Applications outputs in Blocks are typically set either in the brick's code or in the brick's constructor, and changing them in runtime would break this invariant.

Maybe tagging the resulting variable would help?

**Comment by dmitriy-serdyuk** [comment]
`initial_state` function is unusual for blocks, its return name depends on the input.

**Comment by dmitriy-serdyuk** [comment]
Is it better idea to rename initial states in `recurrent` decorator?

**Comment by rizar** [comment]
No sure what you mean by the last entry.

I think that we should think at this point what exactly semantics of `inputs` and `outputs` is. If we decide that both are mandatory, then I would suggest that instead of an `initial_state` method we have `initial_states` method that returns all of them at the same time. If we decide that `outputs` can be optional, then we can introduce a syntax to specify the name of the returned variable.

I like the first direction so far.

**Comment by dmitriy-serdyuk** [comment]
I mean, that usually `initial_state` is called from https://github.com/bartvm/blocks/blob/master/blocks/bricks/recurrent.py#L175 and it is possible to rename it there.

**Comment by rizar** [comment]
That would be mean to make an exception in clear naming policy that we have in Blocks, `brick_application_name`. I am not sure we want that.

The problem is that `initial_state` breaks the general pattern by returning semantically different variables when called with different arguments, IMHO.

**Comment by dmitriy-serdyuk** [comment]
Yes, I agree. So, I'll close this PR and open an issue.

**Pull request closed without merging**
