### PR TITLE
Refactor the Parallel brick

### PR DESCRIPTION
**Pull request by rizar**
This is a first little step in resolving #200. Please look at this refactored `Parallel` brick and tell me if it is crystal clear now what it does or not.

### CODE REVIEW

**Comment by bartvm** [comment]
Great, much better!

The only thing I would consider changing is making the `weights_init` a `Constant(1)` and adding `new_x.eval({x: [1 1]})` and `new_y.eval({y: [2 2 2]})` to the docstring, the output of which should then be `[2 2 2 2]` and `[6 6 6 6 6]`. Always nice to see numerical results with actual shapes.

**Comment by bartvm** [comment]
Shall we merge this?

**Comment by rizar** [comment]
I would like to finish the two other bricks first but got distracted trying to make my phoneme recognition work. But, okay, I will merge it today after checking that it does not break the attention example.

**Comment by bartvm** [comment]
Sure, no rush, was just wondering whether you forgot about this PR or whether there was more to do.

**Comment by rizar** [comment]
Turns out having numerical values in doctests is rather hard because we test with both float32 and float64. We could run doctests only with one of these two values or avoid numerical checks in them.

**Comment by bartvm** [comment]
Ah, just add `# doctest: +ELLIPSIS` to the end of the last docstring command, and give as expected output `array([[ 6.,  6.,  6.,  6.,  6.]]...`

**Comment by rizar** [comment]
Okay, I will finish this refactoring when I have time, but at least the root brick of the hierarchy is now documented.

**Pull request merged**
