### PR TITLE
Temp dump to the right partition

### PR DESCRIPTION
**Pull request by nouiz**
I didn't test it, so make sure to test it before merging.

### CODE REVIEW

**Comment by bartvm** [comment]
What's wrong with dumping to `TMPDIR`? The idea is that even though we don't delete it immediately because we pass `delete=False`, the system should still clear it eventually. This way the user ends up with a strangely named temporary file in the target directory that needs to be deleted manually, right?

If the problem is that you want to delete temporary files, can't we just add `os.remove(temp.name)` at the end?

**Comment by dwf** [comment]
The system SHOULD still clear it eventually. But not at LISA.

TMPDIR is set to /Tmp which is manual cleanup only, which is basically a
technical expression of a disbelief in human nature. :P

**Comment by bartvm** [comment]
*sigh* I guess we can add an `os.remove` at the end, but I don't like the idea of littering user directories with vaguely named temporary files just to deal with the LISA systems' idiosyncrasies.

**Comment by dwf** [comment]
I raise this on @nouiz's pull request in the hope that we can eventually change TMPDIR to an auto-removed directory so as to conform to expectations of practically every application in the world, even if we have /Tmp available for explicit, conscious use.

**Comment by dwf** [comment]
There is an argument for putting the temporary file in the same directory, even if it gets removed eventually: it can help with absolutely catastrophic failure recovery.

**Comment by bartvm** [comment]
Right, I guess that if something goes wrong during the actual copying of the temporary file, it could be useful. Not a big use case though, because the file is very likely to stay in `TMPDIR` till the next reboot, so you can just retrieve it from there yourself if things do go catastrophically wrong.

**Comment by nouiz** [comment]
The problem isn't what you think. At LISA, the temp file get created under
/tmp, not /Tmp. It is way too small, so this fill it up frquently. (a few
people come in the last few days before they pickle files that where taking
Gs and filled /tmp).

If people safe big size stuff, the only place where we can be sure there is
enough space, is at the destination.

**Comment by rizar** [comment]
Wouldn't be better to have a configurable temporary directory for Blocks, e.g. `config.temp_path`? This way people can always set it to '.' in their config when their `/tmp` is small.

**Comment by nouiz** [comment]
By default, I think we should expect that dump can be big and it is
frequent that /tmp is small on cluster.

What you don't like about my fix?

**Comment by bartvm** [comment]
The current fix doesn't remove the temporary file in the end, so you end up with a large number of temporary files (one for each checkpoint) in the target directory that are never removed, right?

**Comment by nouiz** [comment]
There is already a try: except that should take care of that.

But yes, there is very rare case where this can happen.

**Comment by rizar** [comment]
@bartvm, we use `shutil.move`, that is if serialization does not crash, there will be no temporary file left.f

**Comment by bartvm** [comment]
My bad, didn't read the code carefully enough. In that case, this looks fine by me! (Although I'd prefer a more explanatory variable name than `d`).

**Comment by rizar** [comment]
Maybe no intermediate variable altogether?

**Comment by nouiz** [comment]
Done and added a comment

**Comment by dwf** [comment]
@nouiz On LISA `tempfile` creates under `/Tmp` for me.

```
>>> tempfile.mkstemp()
(4, '/Tmp/wardefar/tmpmynv36n_')
```

I think it keys off $TMPDIR, and mine is set to /Tmp/wardefar, and I certainly didn't set it myself.

**Comment by dwf** [comment]
(Yes, just verified it is in `/opt/lisa/os/.local.bashrc`)

**Comment by rizar** [comment]
However, I think it makes sense to use the local directory by default, because it surely has enough space to contain the pickle (since the user dared to run his experiment there).

I would vote for merging this PR.

**Pull request merged**
