### PR TITLE
Adding wer

### PR DESCRIPTION
**Pull request by mohammadpz**
Hi @bartvm ,
I added Word Error Rate to the cost.py but I feel it does not look like your own codes at all :)
Could you please check it and let me know what's missing?

### CODE REVIEW

**Comment by bartvm** [comment]
I'll read the code when I get to the lab, but what are you trying to measure exactly? AFAIK WER is simply how many times you predict the correct word in e.g. an LM. From what I saw, this calculates the edit distance between two sequences instead, which seems something very different to me?

**Comment by rizar** [comment]
Your commit history suggests that you continued your RNN Toy Example. When you want to start another PR before finishing an ongoing one, create another branch by `git branch`.

From the code it looks like it is not a differentiable Theano cost and it does not make sense to wrap in a Brick. Also it is not entirely Block-ish thing: I could imagine such a routine in `blocks-contrib` (see #339) or even more likely in a separate speech recognition repo.

**Comment by mohammadpz** [comment]
@bartvm , so, word error rate in speech recognition is different.
@rizar , my previous PR was on my ```master``` branch. I made another branch but it seems it still have the track of previous commits. Sorry by the way. Let's ask @pbrakel  about it too. @pbrakel , should I add it into another different repo?

**Comment by bartvm** [comment]
Okay, but in that case the problem as @rizar points out is that none of this is differentiable. What you're looking for us a non-Theano monitor channel. This is something that we've kept in mind, but never implemented. This would be the right time to do so :)

Basically, I think you'll want to extend DataStreamMonitoring to execute arbitrary callbacks that take the output of a Theano function and the data stream as an argument, and writing the result to the log. This would also allow for monitoring e.g. BLUE score. The tricky part is that I guess the results of these callbacks also need to be aggregated in a particular way...

**Comment by mohammadpz** [comment]
@bartvm , yes exactly. We don't use ```wer``` for training. We want it to monitor for validation. I can start adding it to the ```DataStreamMonitoring ``` but since I'm new I need your help for better understanding of Blocks :)

**Comment by pbrakel** [comment]
I agree it doesn't really fit in the core of blocks very well. A public speech repo might be an option but the metric might still be common enough for other groups. I originally had contrib in mind for this but a generic monitor for non-theano variables would indeed be needed first (although @dmitriy-serdyuk already wrote something along those lines for our current implementation of the beamsearch).
@mohammadpz sorry for giving you a task that I hadn't thought through enough but I hope you still learned a bit about blocks in the process. At least we know what to do next.

**Comment by mohammadpz** [comment]
@pbrakel , we may talk about this in our speech meeting today. BTW, it's perfectly okay and I still need to learn more about Blocks inner structure. :+1:

**Comment by rizar** [comment]
@mohammadpz , a technical hint: before creating a new branch checkout your master:

```
git checkout master
git branch lets_try_something_new
```
This way I will not have old changes in your new branch.

@pbrakel, `blocks-contrib` is a good place for WER.

Monitoring non-Theano stuff should be included into 0.1 TODO list. And we need a ticket for that, of course. I would argue that Blocks should not care about averaging in this case, since some ways of averaging are just waaay to complex, e.g. BLEU. We should simple call one function for every batch and another to get an aggregated value.

**Comment by bartvm** [comment]
Closing this for now, we'll see it back as a monitoring function later on...

**Comment by rizar** [comment]
Opened #342.

**Pull request closed without merging**
