### PR TITLE
as_dict for epochs

### PR DESCRIPTION
**Pull request by rizar**
An interface fix. It is more convenient to request data as dictionaries for the main loop.

### CODE REVIEW

**Comment by bartvm** [comment]
I'm not a fan of the `epochs()`. As I mentioned earlier, I think that it should be `get_epochs()` then i.e. stick with verbs and verb phrases for methods and functions to make clear what they do, reserve nouns and noun phrases for properties and attributes.

Keep in mind that I actually implemented this for the `get_epoch_iterator` with the `as_dict` keyword argument, so maybe we can just keep `stream.epochs` as a convenience property, but use `get_epoch_iterator(as_dict=True)` in the main loop?

**Comment by rizar** [comment]
I think we come to the point where subjective opinion matters. I like to have a fully functional wrapper over `get_epoch_iterator` that does iteration for me. In fact it is an `__iter__` method.

If you want to rename it to a verb phrase, `iterate_epochs` would work for me.

**Comment by rizar** [comment]
I would like to proceed quickly with this small change. @bartvm , are you fine with `iterate_epochs`?

**Comment by bartvm** [comment]
Yeah.

**Pull request merged**
