### PR TITLE
Make plotting resumable. Fixes #260.

### LINKED ISSUE #260: Plot extensions is incompatible with `blocks-continue`.
Before doing any research I will just post this here:

```
╰─$ python `which blocks-continue` mnist.pkl
Couldn't import dot_parser, loading of dot files will not be possible.

-------------------------------------------------------------------------------
TRAINING HAS BEEN RESUMED
-------------------------------------------------------------------------------
Training status:
	 epochs_done: 5
	 iterations_done: 6000
Log records from the iteration 6000:
	 epoch_took: 7.51784586906
	 final_total_took: 86.6179549694
	 iteration_took: 0.00608396530151
	 saved_to: mnist.pkl
	 test_final_cost: 0.133010807013
	 test_misclassificationrate_apply_error_rate: 0.0364
	 total_took: 36.5187389851
	 train_final_cost: 0.135025526067
	 train_misclassificationrate_apply_error_rate: 0.0355666666667
	 train_total_gradient_norm: 0.564584967867

ERROR:blocks.main_loop:Traceback (most recent call last):
  File "/home/rizar/Dist/blocks/blocks/main_loop.py", line 107, in run
    while self._run_epoch():
  File "/home/rizar/Dist/blocks/blocks/main_loop.py", line 153, in _run_epoch
    self._run_extensions('after_epoch')
  File "/home/rizar/Dist/blocks/blocks/main_loop.py", line 174, in _run_extensions
    extension.dispatch(method_name, *args)
  File "/home/rizar/Dist/blocks/blocks/extensions/__init__.py", line 273, in dispatch
    self.do(callback_invoked, *(from_main_loop + tuple(arguments)))
  File "/home/rizar/Dist/blocks/blocks/extensions/plot.py", line 107, in do
    cursession().store_objects(self.plots[key])
AttributeError: 'NoneType' object has no attribute 'store_objects'
```

### PR DESCRIPTION
**Pull request by bartvm**
@rizar Haven't added tests, but seems to work on both Python 2 and 3 for me.

### CODE REVIEW

**Comment by rizar** [comment]
Great! In order to make it tested it would be nice to put some command that ends the current session in the MNIST example, right before unpickling.

**Comment by bartvm** [comment]
I can't really find a way to close the session... I'll just merge it for now so that this bug is fixed, and maybe we can figure out a better way of testing in the future. Either way the test will be a bit artificial, because in many cases you don't get errors but the plot get's overwritten, not shown, etc. so a full test is impossible either way.

**Comment by rizar** [comment]
Sadly enough, changes from this PR seem to be wiped away by your cPickle PR, @bartvm. Can you do something with it?

**Comment by bartvm** [comment]
Fixed again in 8f932a393bd898a204177575bbec6633c0a6bf4a.

**Pull request merged**
