### PR TITLE
Fixes #484 (renaming after_every_batch and after_every_epoch)

### LINKED ISSUE #484: Condition names and callback names should match?
It is rather annoying that I should write ```extension.set_conditions(after_every_batch=True)``` but ```extension.add_condition('after_batch', predicate, args)```. I guess we should rename `after_every_batch` and `after_every_epoch` to `after_batch` and `after_epoch` respectively.

### PR DESCRIPTION
**Pull request by Thrandis**
Hi,
I renamed after_every_batch to after_batch and after_every_epoch to after_epoch. (Fixes #484)
César

### CODE REVIEW

**Comment by dwf** [comment]
Is this related to a ticket? If so you should put "Fixes #NNN" in the description where NNN is the ticket number.

**Comment by Thrandis** [comment]
Better? :-)

**Comment by dwf** [comment]
Sure. The description rather than the title would have been fine too.
Thanks!

The reason is twofold: one, it makes it easier for anyone potentially
reviewing it. Number two, when we merge this GitHub will automatically
close the ticket, which ensures we don't have stale tickets lying around
after they've been fixed.

**Comment by Thrandis** [comment]
Oh, I didn't knew GitHub closes the ticket automatically. This is a nice feature!
Anyway, thank you for pointing this out!

**Comment by rizar** [comment]
Thanks!

**Pull request merged**
