### PR TITLE
Fix unique name check

### PR DESCRIPTION
**Pull request by rizar**

### CODE REVIEW

**Comment by rizar** [comment]
Right, removed square brackets. Set comprehensions... well, it has not  been yet officially said that we don't support Python 2.7.

**Comment by dwf** [comment]
They are available in Python 2.7:
https://docs.python.org/2/tutorial/datastructures.html#sets

**Comment by rizar** [comment]
Thas was a typo, I wanted to say 2.6, sorry.

**Comment by bartvm** [comment]
Isn't it? We use `OrderedDict`, dictionary comprehensions, multiple context managers in a single `with` statement and `importlib`, all of which are Python 2.7 only. I have no desire whatsoever to support 2.6.

**Comment by rizar** [comment]
Okay, I did not remember for all these things the version in which they were introduced. Changed to set comprehension.

**Comment by bartvm** [comment]
Actually, looks like `variable_names` is zipped at [line 137](https://github.com/rizar/blocks/blob/fix_dataset_evaluator_check/blocks/monitoring/evaluators.py#L137). So it doesn't make sense if you turn it into a set, since those are unordered.

**Comment by rizar** [comment]
Right, thanks for pointing this out, trying again.

**Pull request merged**
