### PR TITLE
Added test for VariableFilter.

### PR DESCRIPTION
**Pull request by Thrandis**
Hey,
Hope it is ok now! (I closed the previous pull request and created this new one! I am still not used to git and github, so I need to work on that).
César

### CODE REVIEW

**Comment by bartvm** [comment]
Did you run into any problem in particular? The process should roughly be:
```
git fetch upstream  # or central, depending on what you called it
git checkout master
git merge upstream/master  # this updates your master
git checkout ccw
git rebase -i master  # this rebase your commits on top of the master
# this pushes your rebased version to your repository
# you need to use -f to force it, because you've rewritten the history
git push -f origin ccw
```

**Comment by Thrandis** [comment]
Yeah I had some merging problems with my repo! How do you force to merge everything to be up to date with the upstream?

**Comment by bartvm** [comment]
```
git checkout master
git reset --hard upstream/master
```
will force your master to be exactly the same as the upstream master

**Comment by Thrandis** [comment]
Ok! I was missing the --hard flag.
And then I can update my github repo by doing "git push -f origin master" ?

**Comment by bartvm** [comment]
Yeah

**Comment by Thrandis** [comment]
Great! Those were the missing pieces! Thanks for the help!

**Pull request merged**
